apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
  labels:
    app: wordpress
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: admin_db  
  WORDPRESS_DB_PASSWORD: root
  WORDPRESS_DB_NAME: wordpressdb
